name: CI
on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
    types:
      - opened
      - synchronize
      - reopened
  workflow_run:
    # without this, the deploy workflow will not run after the auto-merge workflow completes
    workflows: ['Auto-merge']
    types: [completed]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: vx.x.x

      - name: Install dependencies
        run: deno install --quiet

      - name: Spell-check
        uses: crate-ci/typos@master
        with:
          config: ./.github/workflows/typos.toml

      - run: deno task ok

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: vx.x.x

      - name: Publish updated packages
        run: deno publish
